### PR TITLE
Use node to run test.js

### PR DESCRIPTION
**Pull request by cherniavskii**
I was a little bit confused, when saw that I have to run `js test.js` command to build test docs. Not sure if it is a typo or what, but I think it will be more clear, if there will be `node test.js` command

### CODE REVIEW

**Comment by IvanSanchez** [comment]
Using the `node` binary is ambiguous, see https://lists.debian.org/debian-devel-announce/2012/07/msg00002.html and also https://stackoverflow.com/questions/20057790/what-are-the-differences-between-node-js-and-node (and others)

While it might work for you, it will break things for other people. I'd accept a change in the readme if it was a note about it instead.

**Comment by mourner** [comment]
I agree with @cherniavskii that `js script.js` is quite confusing. Maybe we could remove the ambiguity by adding a `test` NPM script? Does `node` in NPM scripts resolve properly in Linux?

**Comment by IvanSanchez** [comment]
Actually, `npm` (or `yarn`) resolve the `js`/`nodejs` binary, so it doesn't have to be specified in the scripts section. Changing that line into `npm test` or `npm run-script test` or even `yarn run test` should work for everybody.

**Comment by cherniavskii** [comment]
@IvanSanchez thanks a lot, your solution is really generic :)

**Pull request closed without merging**
